---
- name: Get encrypted variables
  include_vars: wf_launcher_vars.yml

- name: Get the workflow_job_template_id for the Workflow name
  uri: 
    url: https://{{ ansible_tower_fqdn }}/api/v1/workflow_job_templates/
    method: GET
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    validate_certs: False
    headers:
      Content-Type: "application/json"
    status_code: 200, 201
  register: wjtresults

- debug:
    msg: "{{ wjtresults }}"
    
- name: Assign the workflow_job_id
  set_fact: workflow_job_template_id={{ wjtresults.json | json_query(idquery) }}
  vars:
    - idquery: "results[?(@.name=='{{ workflow_name }}')].id"

- debug:
    msg: "{{ workflow_job_template_id }}"

- name: Job Template to launch a Workflow Job Template
  uri:
    url: https://{{ ansible_tower_fqdn }}/api/v1/workflow_job_templates/{{ workflow_job_template_id }}/launch/
    method: POST
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body:
      extra_vars:
        satHosts:
        - name: newpos
          ipaddr: 192.168.254.220 
          mac: 00:50:56:ff:ff:ff
    body_format: json
    validate_certs: False
    headers:
      Content-Type: "application/json"
    status_code: 200, 201
